models:
  - name: stg_pixel_data
    description: Pixel data
    config: 
      event_time: timestamp_min
      materialized: incremental
      incremental_strategy: microbatch
      lookback: 3
      batch_size: day
      begin: "2025-04-06"
      full_refresh: false  
  - name: stg_campaign_event_data
    description: Gets the campaign events campaign_impressed, campaign_clicked, campaign_converted for placement:linkout & rate type:cpc
    config: 
      event_time: visit_date_utc
      materialized: incremental
      incremental_strategy: microbatch
      lookback: 3
      batch_size: day
      begin: "2025-04-06"
      full_refresh: false
  - name: stg_campaign_with_purchases
    description: Gets the campaign events campaign_impressed, campaign_clicked, campaign_converted for placement:linkout & rate type:cpc with purchase count >0
  - name: int_ltv_data
    description: Analysis with campaign events and pixel data for linkout campaigns
    config:
      event_time: visit_date_utc
      materialized: incremental
      incremental_strategy: microbatch
      lookback: 3
      batch_size: day
      begin: "2025-04-06"
      full_refresh: false
    columns:
      - name: visit_date_utc
        description: Date when occurs a campaign events
      - name: property_name
        description: Property name based on event data
      - name: publisher_visit_id
        description:  Publisher Visit ID
      - name: publisher_id
        description: Publisher ID
      - name: publisher_name
        description: Publisher name based on event data
      - name: utm_source
        description: Utm source (no term when it's blank)
     