models:
  - name: agg_advertiser_campaign_daily
    config: 
      event_time: date
      materialized: incremental
      incremental_strategy: microbatch
      lookback: 3
      batch_size: day
      begin: "2025-04-06"
    columns:
      - name: date
        description: Day in PST
      - name: account_id
        description: Advertiser ID 
      - name: placement_id
        description: Placement ID
      - name: clicks
        description: Total Clicks
      - name: impressions
        description: Total Impressions
      - name: recommendations
        description: Total Recommendations
      - name: conversions
        description: Total Conversions
      - name: advertiser_cost
        description: Advertiser Cost ( Total Revenue)
      - name: zeeto_revenue
        description: Advertiser Cost - Publisher revenue 
      - name: leads_accepted
        description: Total Leads Accepted
      - name: leads_rejected
        description: Total Leads Rejected
      - name: delivery_count
        description: Total Leads (Accepted, Rejected, Failed)
      

